In [1]:
#データフレームは、シリーズをまとめたもの

In [2]:
import pandas as pd

In [3]:
s1 = pd.Series([90,78,45,87,72])
s1

0    90
1    78
2    45
3    87
4    72
dtype: int64

In [4]:
data = [1,2,3,4,5]
s1 = pd.Series(data)
s1

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [5]:
import numpy as np #高速にリストを作るライブラリnumpy

In [6]:
np.arange(1,10,2) #奇数の配列を作成

array([1, 3, 5, 7, 9])

In [8]:
s2 = pd.Series(np.arange(1,10,2))
s2

0    1
1    3
2    5
3    7
4    9
dtype: int64

In [9]:
s1.dtypes

dtype('int64')

In [10]:
s1.index

RangeIndex(start=0, stop=5, step=1)

In [11]:
s1.index = ['sato','suzuki','takagasi','tanaka','ito']

In [12]:
s1

sato        1
suzuki      2
takagasi    3
tanaka      4
ito         5
dtype: int64

In [13]:
dict01 = {'sato':90,'suzuki':99,'takahasi':100,'tanaka':29,'ito':20}

In [16]:
s3 = pd.Series(dict01)
s3

sato         90
suzuki       99
takahasi    100
tanaka       29
ito          20
dtype: int64

In [17]:
s1.values

array([1, 2, 3, 4, 5])

In [18]:
s1['suzuki']

2

In [19]:
s1[0]

1

In [20]:
s1>80

sato        False
suzuki      False
takagasi    False
tanaka      False
ito         False
dtype: bool

In [21]:
s1[s1>80]

Series([], dtype: int64)

In [22]:
s1.size

5

In [23]:
len(s1)

5

In [25]:
s1.index.name = 'member'
s1.name = 'score'
s1

member
sato        1
suzuki      2
takagasi    3
tanaka      4
ito         5
Name: score, dtype: int64

In [26]:
#Series内に同じIndexがある場合四則演算できる

In [27]:
s1+s2

0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
ito        NaN
sato       NaN
suzuki     NaN
takagasi   NaN
tanaka     NaN
dtype: float64

In [29]:
s4 = pd.Series([990,70,74,65,None])
s4

0    990.0
1     70.0
2     74.0
3     65.0
4      NaN
dtype: float64

In [30]:
df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]],
                   columns=['col1','col2','col3'],
                   index=['idx1','idx2','idx3'])
df

col1  col2  col3
idx1     1     2     3
idx2     4     5     6
idx3     7     8     9

In [31]:
df['col1']

idx1    1
idx2    4
idx3    7
Name: col1, dtype: int64

In [32]:
type(df['col1'])

pandas.core.series.Series

In [33]:
s5 = pd.Series({'idx1':10,'idx2':11,'idx3':12})
s5

idx1    10
idx2    11
idx3    12
dtype: int64

In [35]:
df['col4']= s5
df

col1  col2  col3  col4
idx1     1     2     3    10
idx2     4     5     6    11
idx3     7     8     9    12

In [37]:
dates = pd.date_range('2000/01/01',periods = 5 , freq = 'D')#時系列データの作成
dates

DatetimeIndex(['2000-01-01', '2000-01-02', '2000-01-03', '2000-01-04',
               '2000-01-05'],
              dtype='datetime64[ns]', freq='D')

In [38]:
s1.index = dates

In [39]:
s1

2000-01-01    1
2000-01-02    2
2000-01-03    3
2000-01-04    4
2000-01-05    5
Freq: D, Name: score, dtype: int64

In [40]:
#確認問題

In [41]:
name = ['sato','ito']
score = [90,80]
dict01 = {'ito':50,'suzuki':None}
df = pd.DataFrame([[90,75],[60,95]], index=['sato','ito'],columns=['English','Math'])

In [42]:
df

English  Math
sato       90    75
ito        60    95

In [44]:
s1 = pd.Series(score,name)
s1

sato    90
ito     80
dtype: int64

In [45]:
dict1 = pd.Series(dict01)
dict1

ito       50.0
suzuki     NaN
dtype: float64

In [46]:
s1.index

Index(['sato', 'ito'], dtype='object')

In [47]:
dict1.values #.valuesでシリーズの値を取得することができる

array([50., nan])

In [48]:
s1[s1 == 90]

sato    90
dtype: int64

In [49]:
pd.isnull(dict1) #pd.isnullで「Nan」があるか確認することができる

ito       False
suzuki     True
dtype: bool

In [50]:
df['Science'] = s1
df

English  Math  Science
sato       90    75       90
ito        60    95       80